name: uniform_data
description: Uniform data system model.
version: 0.1.1
repository: https://github.com/hestia-io/uniform_data

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  protobuf: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.7
